<a href="https://colab.research.google.com/github/Sehastrajit-clg/Deep-Learning/blob/main/Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [9]:
cd /content/gdrive/My Drive/Colab Notebooks

/content/gdrive/My Drive/Colab Notebooks


In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nnUntitled
import torch.nn.functional as F

In [12]:
df = pd.read_csv('perceptron_sampledata.csv')

In [13]:
X=df.drop('label',axis=1).values
y=df['label'].values

In [15]:
X

array([[ 0.77, -1.14],
       [-0.33,  1.44],
       [ 0.91, -3.07],
       [-0.37, -1.91],
       [-0.63, -1.53],
       [ 0.39, -1.99],
       [-0.49, -2.74],
       [-0.68, -1.52],
       [-0.1 , -3.43],
       [-0.05, -1.95],
       [ 3.88,  0.65],
       [ 0.73,  2.97],
       [ 0.83,  3.94],
       [ 1.59,  1.25],
       [ 1.14,  3.91],
       [ 1.73,  2.8 ],
       [ 1.31,  1.85],
       [ 1.56,  3.85],
       [ 1.23,  2.54],
       [ 1.33,  2.03]])

In [16]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.8)

In [19]:
X_train

tensor([[-0.3300,  1.4400],
        [ 0.8300,  3.9400],
        [ 1.3100,  1.8500],
        [ 0.7700, -1.1400]])

In [20]:
y_train

tensor([0., 1., 1., 0.])

In [18]:
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.FloatTensor(y_train)
y_test = torch.FloatTensor(y_test)

In [23]:
class AND_Model(nn.Module):
  def __init__(self,input_features=2,hidden1=2,hidden2=2,out_features=2):
    super.__init__()
    self.Layer1=nn.Linear(input_features,hidden1)
    self.Layer2=nn.Linear(hidden1,hidden2)
    self.out=nn.Linear(hidden2,out_features)
  def forward(self,x):
    x=F.tanh(self.Layer1(x))
    y=F.tanh(self.Layer2(x))
    x=self.out(x)
    return x

In [ ]:
torch.manual_seed(3)
model=ANN_Model()